### ISSUE TITLE
This is bad form and several faulty assumptions

### ISSUE THREAD

**Issue by akarasulu** [nurik23/ansible_scan_peers#2]
https://github.com/nurik23/ansible-_scan_peers/blob/0f7e6951e5ea41b6b9f4bd769a90b0490c0f57e6/scanpeer.sh#L1

You are testing if you can sudo, this is something that should be already handled for you by Ansible. If you want to do things the right way. Ansible can check for users then you can run your script and don't even need these checks. 

Also you're doing them wrong. The side effect of success means the user exists and I understand that but that's ass backwards. What if sudo is not installed but the user exists? There are unix commands like `id` to check for the presence of an account.

Also, you've totally forgotten that you will be categorizing peers using Ansible's inventory right? So then why are you adding this logic. You need to look at how you run different scripts based on the environment category. You don't need all these checks at all. 

This is completely the wrong way to do this but it will work as a really dirty approach for now. You need to look at specific Ansible functionality and features to do this right and the actual shell code becomes two maybe three lines maximum.

**Comment by nurik23** [comment]
done
