### ISSUE TITLE
Why use the MASTER_ prefix? Why not just RAM and CPU?

### ISSUE THREAD

**Issue by akarasulu** [nurik23/ansible_scan_peers#5]
Ahh that's right you copied it like a bitch. Don't copy paste shit. 

Also fix the formatting ... this is just disgusting.

https://github.com/nurik23/ansible-_scan_peers/blob/326a3698c1ad060e6afd3812393e84eb7fb336c0/Vagrantfile#L5

**Comment by nurik23** [comment]
done
